export const sources = [
  { code: 'AAG', name: "Astral Adventurer's Guide" },
  { code: 'AATM', name: 'Adventure Atlas: The Mortuary' },
  { code: 'AI', name: 'Acquisitions Incorporated' },
  { code: 'AL', name: "Adventurers' League" },
  { code: 'ALCoS', name: 'Adventurers League: Curse of Strahd' },
  { code: 'ALEE', name: 'Adventurers League: Elemental Evil' },
  { code: 'ALRoD', name: 'Adventurers League: Rage of Demons' },
  { code: 'AWM', name: 'Adventure with Muk' },
  { code: 'AZfyT', name: 'A Zib for your Thoughts' },
  { code: 'AitFR', name: 'Adventures in the Forgotten Realms' },
  { code: 'AitFR-AVT', name: 'Adventures in the Forgotten Realms: A Verdant Tomb' },
  { code: 'AitFR-DN', name: 'Adventures in the Forgotten Realms: Deepest Night' },
  { code: 'AitFR-FCD', name: 'Adventures in the Forgotten Realms: From Cyan Depths' },
  { code: 'AitFR-ISF', name: 'Adventures in the Forgotten Realms: In Scarlet Flames' },
  { code: 'AitFR-THP', name: 'Adventures in the Forgotten Realms: The Hidden Page' },
  { code: 'BAM', name: "Boo's Astral Menagerie" },
  { code: 'BGDIA', name: "Baldur's Gate: Descent Into Avernus" },
  { code: 'BGG', name: 'Bigby Presents: Glory of the Giants' },
  { code: 'BMT', name: 'The Book of Many Things' },
  { code: 'CM', name: 'Candlekeep Mysteries' },
  { code: 'CRCotN', name: 'Critical Role: Call of the Netherdeep' },
  { code: 'CoA', name: 'Chains of Asmodeus' },
  { code: 'CoS', name: 'Curse of Strahd' },
  { code: 'DC', name: 'Divine Contention' },
  { code: 'DD', name: 'Dangerous Designs' },
  { code: 'DIP', name: 'Dragon of Icespire Peak' },
  { code: 'DMG', name: "Dungeon Master's Guide" },
  { code: 'DMTCRG', name: 'The Deck of Many Things: Card Reference Guide' },
  { code: 'DSotDQ', name: 'Dragonlance: Shadow of the Dragon Queen' },
  { code: 'DoD', name: 'Domains of Delight' },
  { code: 'DoDk', name: 'Dungeons of Drakkenheim' },
  { code: 'DoSI', name: 'Dragons of Stormwreck Isle' },
  { code: 'EEPC', name: "Elemental Evil Player's Companion" },
  { code: 'EET', name: 'Elemental Evil: Trinkets' },
  { code: 'EFR', name: 'Eberron: Forgotten Relics' },
  { code: 'EGW', name: "Explorer's Guide to Wildemount" },
  { code: 'EGW_DD', name: 'Dangerous Designs' },
  { code: 'EGW_FS', name: 'Frozen Sick' },
  { code: 'EGW_ToR', name: 'Tide of Retribution' },
  { code: 'EGW_US', name: 'Unwelcome Spirits' },
  { code: 'ERLW', name: 'Eberron: Rising from the Last War' },
  { code: 'ESK', name: 'Essentials Kit' },
  { code: 'FS', name: 'Frozen Sick' },
  { code: 'FTD', name: "Fizban's Treasury of Dragons" },
  { code: 'GGR', name: "Guildmasters' Guide to Ravnica" },
  { code: 'GHLoE', name: 'Grim Hollow: Lairs of Etharis' },
  { code: 'GoS', name: 'Ghosts of Saltmarsh' },
  { code: 'GotSF', name: 'Giants of the Star Forge' },
  { code: 'HAT-LMI', name: 'Honor Among Thieves: Legendary Magic Items' },
  { code: 'HAT-TG', name: "Honor Among Thieves: Thieves' Gallery" },
  { code: 'HF', name: "Heroes' Feast" },
  { code: 'HFFotM', name: "Heroes' Feast Flavors of the Multiverse" },
  { code: 'HFStCM', name: "Heroes' Feast: Saving the Children's Menu" },
  { code: 'HWAitW', name: 'Humblewood: Adventure in the Wood' },
  { code: 'HWCS', name: 'Humblewood Campaign Setting' },
  { code: 'HftT', name: 'Hunt for the Thessalhydra' },
  { code: 'HoL', name: 'The House of Lament' },
  { code: 'HotDQ', name: 'Hoard of the Dragon Queen' },
  { code: 'IDRotF', name: 'Icewind Dale: Rime of the Frostmaiden' },
  { code: 'IMR', name: 'Infernal Machine Rebuild' },
  { code: 'JttRC', name: 'Journeys through the Radiant Citadel' },
  { code: 'KKW', name: "Krenko's Way" },
  { code: 'KftGV', name: 'Keys from the Golden Vault' },
  { code: 'LK', name: 'Lightning Keep' },
  { code: 'LLK', name: 'Lost Laboratory of Kwalish' },
  { code: 'LMoP', name: 'Lost Mine of Phandelver' },
  { code: 'LR', name: 'Locathah Rising' },
  { code: 'LoX', name: 'Light of Xaryxis' },
  { code: 'MCV1SC', name: 'Monstrous Compendium Volume 1: Spelljammer Creatures' },
  { code: 'MCV2DC', name: 'Monstrous Compendium Volume 2: Dragonlance Creatures' },
  { code: 'MCV3MC', name: 'Monstrous Compendium Volume 3: Minecraft Creatures' },
  { code: 'MCV4EC', name: 'Monstrous Compendium Volume 3: 4: Eldraine Creatures' },
  { code: 'MFF', name: "Mordenkainen's Fiendish Folio" },
  { code: 'MGELFT', name: "Muk's Guide To Everything He Learned From Tasha" },
  { code: 'MM', name: 'Monster Manual' },
  { code: 'MOT', name: 'Mythic Odysseys of Theros' },
  { code: 'MPMM', name: 'Mordenkainen Presents: Monsters of the Multiverse' },
  { code: 'MPP', name: "Morte's Planar Parade" },
  { code: 'MTF', name: "Mordenkainen's Tome of Foes" },
  { code: 'MaBJoV', name: "Minsc and Boo's Journal of Villainy" },
  { code: 'MisMV1', name: 'Misplaced Monsters: Volume 1' },
  { code: 'NRH', name: 'NERDS Restoring Harmony' },
  { code: 'NRH-ASS', name: 'NERDS Restoring Harmony: A Sticky Situation' },
  { code: 'NRH-AT', name: 'NERDS Restoring Harmony: Adventure Together' },
  { code: 'NRH-AVitW', name: 'NERDS Restoring Harmony: A Voice in the Wilderness' },
  { code: 'NRH-AWoL', name: 'NERDS Restoring Harmony: A Web of Lies' },
  { code: 'NRH-CoI', name: 'NERDS Restoring Harmony: Circus of Illusions' },
  { code: 'NRH-TCMC', name: 'NERDS Restoring Harmony: The Candy Mountain Caper' },
  { code: 'NRH-TLT', name: 'NERDS Restoring Harmony: The Lost Tomb' },
  { code: 'OGA', name: 'One Grung Above' },
  { code: 'OoW', name: 'The Orrery of the Wanderer' },
  { code: 'OotA', name: 'Out of the Abyss' },
  { code: 'PHB', name: "Player's Handbook" },
  { code: 'PSA', name: 'Plane Shift: Amonkhet' },
  { code: 'PSD', name: 'Plane Shift: Dominaria' },
  { code: 'PSI', name: 'Plane Shift: Innistrad' },
  { code: 'PSK', name: 'Plane Shift: Kaladesh' },
  { code: 'PSX', name: 'Plane Shift: Ixalan' },
  { code: 'PSZ', name: 'Plane Shift: Zendikar' },
  { code: 'PaBTSO', name: 'Phandelver and Below: The Shattered Obelisk' },
  { code: 'PiP', name: 'Peril in Pinegrove' },
  { code: 'PotA', name: 'Princes of the Apocalypse' },
  { code: 'RMBRE', name: 'The Lost Dungeon of Rickedness: Big Rick Energy' },
  { code: 'RMR', name: 'Dungeons &amp; Dragons vs. Rick and Morty: Basic Rules' },
  { code: 'RoT', name: 'The Rise of Tiamat' },
  { code: 'RoTOS', name: 'The Rise of Tiamat Online Supplement' },
  { code: 'RtG', name: 'Return to Glory' },
  { code: 'SAC', name: 'Sage Advice Compendium' },
  { code: 'SADS', name: 'Sapphire Anniversary Dice Set' },
  { code: 'SAiS', name: 'Spelljammer: Adventures in Space' },
  { code: 'SCAG', name: "Sword Coast Adventurer's Guide" },
  { code: 'SCC', name: 'Strixhaven: A Curriculum of Chaos' },
  { code: 'SCC-ARiR', name: 'A Reckoning in Ruins' },
  { code: 'SCC-CK', name: 'Campus Kerfuffle' },
  { code: 'SCC-HfMT', name: 'Hunt for Mage Tower' },
  { code: 'SCC-TMM', name: "The Magister's Masquerade" },
  { code: 'SCREEN', name: "Dungeon Master's Screen" },
  { code: 'SCREEN_DUNGEON_KIT', name: "Dungeon Master's Screen: Dungeon Kit" },
  { code: 'SCREEN_WILDERNESS_KIT', name: "Dungeon Master's Screen: Wilderness Kit" },
  { code: 'SDW', name: "Sleeping Dragon's Wake" },
  { code: 'SJA', name: 'Spelljammer Academy' },
  { code: 'SKT', name: "Storm King's Thunder" },
  { code: 'SLW', name: "Storm Lord's Wrath" },
  { code: 'SRC_SCREEN_SPELLJAMMER', name: 'ScreenSpelljammer' },
  { code: 'SatO', name: 'Sigil and the Outlands' },
  { code: 'SjA', name: 'Spelljammer Academy' },
  { code: 'TCE', name: "Tasha's Cauldron of Everything" },
  { code: 'TDCSR', name: "Tal'Dorei Campaign Setting Reborn" },
  { code: 'TLK', name: 'The Lost Kenku' },
  { code: 'TTP', name: 'The Tortle Package' },
  { code: 'TftYP', name: 'Tales from the Yawning Portal' },
  { code: 'TftYP-AtG', name: 'Tales from the Yawning Portal: Against the Giants' },
  { code: 'TftYP-DiT', name: 'Tales from the Yawning Portal: Dead in Thay' },
  { code: 'TftYP-TFoF', name: 'Tales from the Yawning Portal: The Forge of Fury' },
  { code: 'TftYP-THSoT', name: 'Tales from the Yawning Portal: The Hidden Shrine of Tamoachan' },
  { code: 'TftYP-TSC', name: 'Tales from the Yawning Portal: The Sunless Citadel' },
  { code: 'TftYP-ToH', name: 'Tales from the Yawning Portal: Tomb of Horrors' },
  { code: 'TftYP-WPM', name: 'Tales from the Yawning Portal: White Plume Mountain' },
  { code: 'ToA', name: 'Tomb of Annihilation' },
  { code: 'ToD', name: 'Tyranny of Dragons' },
  { code: 'ToFW', name: "Turn of Fortune's Wheel" },
  { code: 'ToR', name: 'Tide of Retribution' },
  { code: 'UA20F', name: 'Unearthed Arcana: 2020 Feats' },
  { code: 'UA20POR', name: 'Unearthed Arcana: 2020 Psionic Options Revisited' },
  { code: 'UA20SC1', name: 'Unearthed Arcana: 2020 Subclasses: Part 1' },
  { code: 'UA20SC2', name: 'Unearthed Arcana: 2020 Subclasses: Part 2' },
  { code: 'UA20SC3', name: 'Unearthed Arcana: 2020 Subclasses: Part 3' },
  { code: 'UA20SC4', name: 'Unearthed Arcana: 2020 Subclasses: Part 4' },
  { code: 'UA20SC5', name: 'Unearthed Arcana: 2020 Subclasses: Part 5' },
  { code: 'UA20SCR', name: 'Unearthed Arcana: 2020 Subclasses Revisited' },
  { code: 'UA20SMT', name: 'Unearthed Arcana: 2020 Spells and Magic Tattoos' },
  { code: 'UA21DO', name: 'Unearthed Arcana: 2021 Draconic Options' },
  { code: 'UA21FF', name: 'Unearthed Arcana: 2021 Folk of the Feywild' },
  { code: 'UA21GL', name: 'Unearthed Arcana: 2021 Gothic Lineages' },
  { code: 'UA21MoS', name: 'Unearthed Arcana: 2021 Mages of Strixhaven' },
  { code: 'UA21TotM', name: 'Unearthed Arcana: 2021 Travelers of the Multiverse' },
  { code: 'UA22GO', name: 'Unearthed Arcana: 2022 Giant Options' },
  { code: 'UA22HoK', name: 'Unearthed Arcana: 2022 Heroes of Krynn' },
  { code: 'UA22HoKR', name: 'Unearthed Arcana: 2022 Heroes of Krynn Revisited' },
  { code: 'UA22WotM', name: 'Unearthed Arcana: 2022 Wonders of the Multivers' },
  { code: 'UA3PE', name: 'Unearthed Arcana: Three-Pillar Experience' },
  { code: 'UAA', name: 'Unearthed Arcana: Artificer' },
  { code: 'UAAR', name: 'Unearthed Arcana: Artificer Revisited' },
  { code: 'UAATOSC', name: 'Unearthed Arcana: A Trio of Subclasses' },
  { code: 'UABAM', name: 'Unearthed Arcana: Barbarian and Monk' },
  { code: 'UABAP', name: 'Unearthed Arcana: Bard and Paladin' },
  { code: 'UABBC', name: 'Unearthed Arcana: Bard: Bard Colleges' },
  { code: 'UABPP', name: 'Unearthed Arcana: Barbarian Primal Paths' },
  { code: 'UACAM', name: 'Unearthed Arcana: Centaurs and Minotaurs' },
  { code: 'UACDD', name: 'Unearthed Arcana: Cleric: Divine Domains' },
  { code: 'UACDW', name: 'Unearthed Arcana: Cleric, Druid, and Wizard' },
  { code: 'UACFV', name: 'Unearthed Arcana: Class Feature Variants' },
  { code: 'UAD', name: 'Unearthed Arcana: Druid' },
  { code: 'UAEAG', name: 'Unearthed Arcana: Eladrin and Gith' },
  { code: 'UAEBB', name: 'Unearthed Arcana: Eberron' },
  { code: 'UAESR', name: 'Unearthed Arcana: Elf Subraces' },
  { code: 'UAF', name: 'Unearthed Arcana: Fighter' },
  { code: 'UAFFR', name: 'Unearthed Arcana: Feats for Races' },
  { code: 'UAFFS', name: 'Unearthed Arcana: Feats for Skills' },
  { code: 'UAFO', name: 'Unearthed Arcana: Fiendish Options' },
  { code: 'UAFRR', name: 'Unearthed Arcana: Fighter, Ranger, and Rogue' },
  { code: 'UAFRW', name: 'Unearthed Arcana: Fighter, Rogue, and Wizard' },
  { code: 'UAFT', name: 'Unearthed Arcana: Feats' },
  { code: 'UAGH', name: 'Unearthed Arcana: Gothic Heroes' },
  { code: 'UAGHI', name: 'Unearthed Arcana: Greyhawk Initiative' },
  { code: 'UAGSS', name: 'Unearthed Arcana: Giant Soul Sorcerer' },
  { code: 'UAKOO', name: 'Unearthed Arcana: Kits of Old' },
  { code: 'UALDR', name: 'Unearthed Arcana: Light, Dark, Underdark!' },
  { code: 'UAM', name: 'Unearthed Arcana: Monk' },
  { code: 'UAMAC', name: 'Unearthed Arcana: Mass Combat' },
  { code: 'UAMC', name: 'Unearthed Arcana: Modifying Classes' },
  { code: 'UAMDM', name: 'Unearthed Arcana: Modern Magic' },
  { code: 'UAOD', name: 'Unearthed Arcana: Order Domain' },
  { code: 'UAOSS', name: 'Unearthed Arcana: Of Ships and the Sea' },
  { code: 'UAP', name: 'Unearthed Arcana: Paladin' },
  { code: 'UAPCRM', name: 'Unearthed Arcana: Prestige Classes and Rune Magic' },
  { code: 'UAR', name: 'Unearthed Arcana: Ranger' },
  { code: 'UARAR', name: 'Unearthed Arcana: Ranger and Rogue' },
  { code: 'UARCO', name: 'Unearthed Arcana: Revised Class Options' },
  { code: 'UARSC', name: 'Unearthed Arcana: Revised Subclasses' },
  { code: 'UARoE', name: 'Unearthed Arcana: Races of Eberron' },
  { code: 'UARoR', name: 'Unearthed Arcana: Races of Ravnica' },
  { code: 'UAS', name: 'Unearthed Arcana: Sorcerer' },
  { code: 'UASAW', name: 'Unearthed Arcana: Sorcerer and Warlock' },
  { code: 'UASIK', name: 'Unearthed Arcana: Sidekicks' },
  { code: 'UASSP', name: 'Unearthed Arcana: Starter Spells' },
  { code: 'UATF', name: 'Unearthed Arcana: The Faithful' },
  { code: 'UATMC', name: 'Unearthed Arcana: The Mystic Class' },
  { code: 'UATOBM', name: 'Unearthed Arcana: That Old Black Magic' },
  { code: 'UATRR', name: 'Unearthed Arcana: The Ranger, Revised' },
  { code: 'UATSC', name: 'Unearthed Arcana: Three Subclasses' },
  { code: 'UAVR', name: 'Unearthed Arcana: Variant Rules' },
  { code: 'UAWA', name: 'Unearthed Arcana: Waterborne Adventures' },
  { code: 'UAWAW', name: 'Unearthed Arcana: Warlock and Wizard' },
  { code: 'UAWGE', name: "Wayfinder's Guide to Eberron" },
  { code: 'UAWR', name: 'Unearthed Arcana: Wizard Revisited' },
  { code: 'US', name: 'Unwelcome Spirits' },
  { code: 'VD', name: 'Vecna Dossier' },
  { code: 'VGM', name: "Volo's Guide to Monsters" },
  { code: 'VRGR', name: "Van Richten's Guide to Ravenloft" },
  { code: 'WBtW', name: 'The Wild Beyond the Witchlight' },
  { code: 'WDH', name: 'Waterdeep: Dragon Heist' },
  { code: 'WDMM', name: 'Waterdeep: Dungeon of the Mad Mage' },
  { code: 'XGE', name: "Xanathar's Guide to Everything" },
  { code: 'XMtS', name: 'X Marks the Spot' }
] as const;
